services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mtx
    restart: always
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_PROTOCOLS=tcp
    networks:
      - app-network
    
  streaming-server:
    image: sunghoon02/conways-streaming-server:mouse
    container_name: node
    restart: always
    command: node server.js
    ports:
      - "2000:2000"
    networks:
      - app-network

  game:
    image: sunghoon02/conways-game-of-life:ws2
    container_name: game
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    
networks:
  app-network:
    